### ISSUE TITLE
Google - Could not load the default credentials 

### ISSUE THREAD

**Issue by agent-z28** [ephraimm/n8n-nodes-google-document-ai#1]
I set up the google Account. Tested it via Python API.

In n8n v1.67.1 : I  installed the [n8n-nodes-google-document-ai](https://github.com/ephraimm/n8n-nodes-google-document-ai) extension.

 I propperly Set Up the Google Account:

![image](https://github.com/user-attachments/assets/a80eb7f3-f64d-4efc-adf8-5edead5fd809)

I followed the Documentation and i added the 3 Lines Key.

Still I get Everytime this Error:
![image](https://github.com/user-attachments/assets/6800b618-e841-490a-a3ab-1bd580e77946)

```NodeOperationError: Internal error
    at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-google-document-ai/nodes/GoogleDocumentAI/GoogleDocumentAI.node.ts:222:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:704:51
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1134:20
Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/home/node/.n8n/nodes/node_modules/google-auth-library/build/src/auth/googleauth.js:287:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at GoogleAuth._GoogleAuth_determineClient (/home/node/.n8n/nodes/node_modules/google-auth-library/build/src/auth/googleauth.js:834:32)```

**Comment by agent-z28** [comment]
@ephraimm do you have an idea what could be the reason ?

**Comment by agent-z28** [comment]
I found out, once i pass the google-key file to the docker-environment, it works!

I always wonder about this google authentification.. At the end whats the idea of providing the authetification on environment leven and then on node-plugin level again ?

**Comment by ephraimm** [comment]
> I found out, once i pass the google-key file to the docker-environment, it works!
> 
> I always wonder about this google authentification.. At the end whats the idea of providing the authentification on environment leven and then on node-plugin level again ?

Hi @agent-z28 
This is a work in progress, ultimately I'd like to implement the setup of google account with credentials in order for this to be used on cloud, running your own instance with the key file works.

Let me know if there is any other tweaks needed

**Comment by agent-z28** [comment]
@ephraimm thank you!

Actually i run into another Problem:

![image](https://github.com/user-attachments/assets/b6e9ef93-d398-4a61-860d-242180cc45e7)

This line seems to be not working:

https://github.com/ephraimm/n8n-nodes-google-document-ai/blob/master/nodes/GoogleDocumentAI/GoogleDocumentAI.node.ts#L206

http://localhost:5678/
Internal error
NodeOperationError: Internal error
    at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-google-document-ai/nodes/GoogleDocumentAI/GoogleDocumentAI.node.ts:222:12)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:704:51
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1134:20
this.processPageData is not a function
TypeError: this.processPageData is not a function
    at /home/node/.n8n/nodes/node_modules/n8n-nodes-google-document-ai/nodes/GoogleDocumentAI/GoogleDocumentAI.node.ts:206:53
    at Array.map (<anonymous>)
    at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-google-document-ai/nodes/GoogleDocumentAI/GoogleDocumentAI.node.ts:206:29)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:704:51
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1134:20

i can create another issue

**Comment by ephraimm** [comment]
pls, working on this
